### PR TITLE
Rewriting to be Stateless

### LINKED ISSUE #7: Add retry logic to getVehicleIDFromVin
The car can be asleep and fails to return this endpoint. Should add some retry logic.

### PR DESCRIPTION
**Pull request by scottrobertson**
Now you need to pass an Access Token to every API call. This is super easy now due to the "Auth for Tesla" app exposing an "Get Access Token" action in Shortcuts app.

This also allows the removal of all env var configs.

Settings are now controlled via headers, as it's much nicer to use them in iOS/macOS shortcuts vs query params.

An example of how this can be used in iOS/macOS Shortcuts

2021-11-07 at 22 44 59

### CODE REVIEW

**Comment by scottrobertson** [comment]
@adamlogic you still using this? I am wondering if this would be easier for you.

**Comment by adamlogic** [comment]
Hey @scottrobertson! Yes, I do still use this. I'm currently in Denver for RubyConf, but I'll give this a try when I get back.

**Comment by scottrobertson** [comment]
@adamlogic awesome :) 

I have noticed one issue with the `vehicles` endpoint when the car is sleeping, so I may need to add some retry logic to that. Didn't happen before as it was cached.

**Comment by adamlogic** [comment]
Hey @scottrobertson! I finally got around to this, and it's working great! I'm using your workers endpoint now as well. 🙌

I don't have much experience with Shortcuts at all, so I'm not sure if there's any way around needing to acknowledge "get access token" each time. Also I think I screwed up the notification at the end. 🤷‍♂️ 

Either way, it gets the job done. Thanks!

https://user-images.githubusercontent.com/372/149641117-3350ac04-a39d-4945-89c8-28ae9f3e9f14.mov

**Comment by scottrobertson** [comment]
Hey @adamlogic 

Thanks :)

And you can turn that off. If you click the little arrow next to the "get access token" action and then disable "show when run".

**Comment by adamlogic** [comment]
Oh, awesome! And I also cleaned up the response notification by adding a "get dictionary value" step after "get dictionary". I had no idea Shortcuts could do all this. :-)

**Pull request merged**
